[package]
name = "wav_dominant_freq_viewer"
version = "0.4.0"
edition = "2024"

[dependencies]
hound = "3.5"
rustfft = "6.1"
rodio = "0.17"
eframe = "0.33.0"   # egui 的应用框架
#egui_plot = { path = "../egui_plot/egui_plot" }
egui_plot = "0.34"
egui-chinese-font = { path = "../egui-chinese-font" }
